### ISSUE TITLE
MapX V5: list of "Priority 1" bugs

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#255]
- [ ] Story maps with read access != "public" cannot be opened by public users when they are shared with the specific URL.
- [ ] Story maps published in a private project with read access = "public" cannot be shared with public users.
- [x] Legends of raster views are not always displayed in full: https://mvp.app.mapx.org?project=MX-9PB-WC2-FUG-KOB-CY4&views=MX-S3UDS-YVMCG-FB4JW
- [x] Publishers should be able to create new collections. For now, only admins of the project can.
- [x] Add the project name in label of view available in story map editor
- [x] Download data: "Country used to spatially select the data. By default = entire world" for now it's not the case, by default = current project (highlighted countries).
- [x] Upload data - drag and drop method: doesn't work
- [ ] Upload data - upload module: Shapefile, GeoJSON, GPKG -> OK;  GPX, KML – not OK (see #413)
- [x] WMS generator in raster view responds with "null" when layers are demanded.
- [x] ~The design of the views on several columns doesn't work with Firefox~

**Comment by fxi** [comment]
The uploader should return some messages when the upload fails. Could you report those messages as comment ? 
The subset by country, I have to change the label or the behaviour ?

**Comment by thomaspiller** [comment]
For the subset by country, I talked to @PierreLacroix  and we think it's the label that should be changed.

**Comment by thomaspiller** [comment]
Example of message returned by the uploader ([id] replaces real values):
```
Upload done. Importation in DB, please wait, this could take a while...

MapX authentication:  user [id] authentification in project [id]  : ok.

Conversion using ogr2ogr : please wait ...

FAILURE:
Unable to open datasource `1531998955929_cod_concession_simple.gpx' with the following drivers.

  -> `PCIDSK'

  -> `PDF'

  -> `MBTiles'

  -> `ESRI Shapefile'

  -> `MapInfo File'

  -> `UK .NTF'

  -> `OGR_SDTS'

  -> `S57'

  -> `DGN'

  -> `OGR_VRT'

  -> `REC'

  -> `Memory'

  -> `BNA'

  -> `CSV'

  -> `GML'

  -> `GPX'

  -> `KML'

  -> `GeoJSON'

  -> `ESRIJSON'

  -> `TopoJSON'

  -> `OGR_GMT'

  -> `GPKG'

  -> `SQLite'

  -> `WAsP'

  -> `PostgreSQL'

  -> `OpenFileGDB'

  -> `XPlane'

  -> `DXF'

  -> `CAD'

  -> `Geoconcept'
  -> `GeoRSS'
  -> `GPSTrackMaker'
  -> `VFK'
  -> `PGDUMP'
  -> `OSM'
  -> `GPSBabel'
  -> `SUA'
  -> `OpenAir'
  -> `OGR_PDS'
  -> `WFS'
  -> `WFS3'
  -> `HTF'
  -> `AeronavFAA'
  -> `EDIGEO'
  -> `GFT'
  -> `SVG'
  -> `CouchDB'
  -> `Cloudant'
  -> `Idrisi'
  -> `ARCGEN'
  -> `SEGUKOOA'
  -> `SEGY'
  -> `ElasticSearch'
  -> `Carto'
  -> `AmigoCloud'
  -> `SXF'
  -> `Selafin'
  -> `JML'
  -> `PLSCENES'
  -> `CSW'
  -> `VDV'
  -> `MVT'
  -> `TIGER'
  -> `AVCBin'
  -> `AVCE00'
  -> `HTTP'
```

**Comment by fxi** [comment]
### Multi column

What is not working ? Please be a little more specific.

*Firefox 61* works : 
![image](https://user-images.githubusercontent.com/1196833/42945682-45d59106-8b69-11e8-8351-f5303d87bd1f.png)
Safari 11.1 works : 
![image](https://user-images.githubusercontent.com/1196833/42946409-11e4b820-8b6b-11e8-8645-8eeb260e9fe0.png)

*Chrome 67* works:
![image](https://user-images.githubusercontent.com/1196833/42945804-9c1b1220-8b69-11e8-8346-431fc285b587.png)

*Vivaldi 1.5*  works:
![image](https://user-images.githubusercontent.com/1196833/42946287-ce707eda-8b6a-11e8-8ee6-e5d67d8893df.png)

*Edge 41.16* works ( gracefully fallback on one column, which is expected )
![image](https://user-images.githubusercontent.com/1196833/42946097-60ecd91c-8b6a-11e8-9939-47e57a092ad6.png)

**Comment by thomaspiller** [comment]
I don't have the same result on Firefox 61.0.1 (64-bit) Windows 10:
![image](https://user-images.githubusercontent.com/19908801/42947422-93c4d134-8b6d-11e8-99a1-509405236a86.png)
![image](https://user-images.githubusercontent.com/19908801/42947456-a3979bd2-8b6d-11e8-8248-5e87f375d1e3.png)

**Comment by fxi** [comment]
Using the latest version ?

**Comment by thomaspiller** [comment]
My bad, you're right. I was on mvp version.

**Comment by fxi** [comment]
@thomaspiller no problem, the test version is quite new and maybe you dont update your containers very often. In your docker-compose file, you could try to have a test_app service and update it automatically using watchtower : https://github.com/v2tec/watchtower

Eg.

```yml
version: "3.2"
 [...]
services:
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: test_app --interval 3600
  test_app:
    env_file: mapx.dev.env
    image: fredmoser/mx-app-shiny:debian
    restart: always
    ports:
      - 3838
    hostname: mx_app
    depends_on:
      - pg
      - traefik
    labels:
      - traefik.s1.frontend.rule=Host:test_app.mapx.localhost
      - traefik.s1.port=3838
    volumes:
      - shared:/shared
[...]
```

Or you can launch manually a docker instance that use whatchtower : 

```sh
docker run -d \
  --name watchtower \
  -v /var/run/docker.sock:/var/run/docker.sock \
  v2tec/watchtower test_app

```
