### ISSUE TITLE
Remove style from categories when views are filtered

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#639]
In a project with categories, when the views are filtered, the background as well as the colored border of the views belonging to a category should be removed.

![image](https://user-images.githubusercontent.com/19908801/104288199-c8d3bc80-54b7-11eb-9ade-ba255138794e.png)

**Comment by thomaspiller** [comment]
The new panel layout is great. There is however a small problem, the colored borders are no longer available in "unfiltered" mode.
![image](https://user-images.githubusercontent.com/19908801/104919948-57a07780-5997-11eb-9c7a-1357e3f64a98.png)

**Comment by fxi** [comment]
The category color applies now only to the ... caret. We could color the border of the caret container:
![image](https://user-images.githubusercontent.com/1196833/104921003-04c7bf80-5999-11eb-93e9-de68ea080497.png)
View container item border is hard do design properly: it become very visually heavy very quickly. 
But I can put it back, left or right pseudo element or left or right border.

**Comment by antobenve** [comment]
I think I see a related issue: the color of the arrow of a category group is always black (default) until the color is changed after the new release.

**Comment by thomaspiller** [comment]
I confirm @antobenve findings.
If we keep the caret option, I think that adding the colored circle would be a good idea.

**Comment by fxi** [comment]
or .. discrete line on the left of the header :
![image](https://user-images.githubusercontent.com/1196833/104926707-ca622080-59a0-11eb-96f6-eeee8c35e7d0.png)

**Comment by thomaspiller** [comment]
Based on your two screenshots, I prefer the discrete line.
Once the category has been expanded, does the line cover the entire height?

**Comment by fxi** [comment]
Nope. Just the header's height:

```css
.li-group-header {
    font-size: 1em;
    width: 100%;
    display: flex;
    align-items: center;
    border-left: 1px solid #f0f;
}
```
![image](https://user-images.githubusercontent.com/1196833/104929782-9e489e80-59a4-11eb-9b38-e044e1ec7fce.png)

But I can re-add a pseudo element on the full height:
```css
li-group:after {
    content: '';
    position: absolute;
    top: 10px;
    bottom: 10px;
    border-left: 1px solid #f0f;
}
```

![image](https://user-images.githubusercontent.com/1196833/104930876-f8962f00-59a5-11eb-85e1-0c85f4fdcb38.png)
