### ISSUE TITLE
Store and allow usage of a common locations definition

### ISSUE THREAD

**Issue by trepmag** [unep-grid/map-x-mgl#678]
It appears that, within the sdk (but might be helpful elsewhere, e.g.: custom code view), some map behaviors such as `flyTo` or `fitBounds` would benefit to use **common locations** such as the following one:
- ISO3 country codes
- M49 which includes areas (e.g.: Africa, Latin America and the Caribbean, etc, ...)

Each of these common location would store a specific zoom+center and/or bounds coordinates and then could be use as parameter for Mapbox's `flyto()` or `fitBounds()` methods and thus prevent the redefining these parameters all over the places...

As such, [this dashboard](https://dash.unepgrid.ch/superset/dashboard/74/) expose a data visualisation with the [superset mapx plugin](https://git.unepgrid.ch/grid-p/superset-plugin-chart-mapx) using a region filter on which the location is mapped as follow to trigger flyto behaviors; excerpt:
```yaml
...
- methods:
  - name: map_fly_to
    parameters:
      lon: 11.496
      lat: 1.172
      zoom: 1.475
  condition: "has all {{ regions_name }} == 'Africa'"
- methods:
  - name: map_fly_to
    parameters:
      lon: 117.033
      lat: 3.662
      zoom: 1.475
  condition: "has all {{ regions_name }} == 'Asia and the Pacific'"
...
```

To prevent the definition of those locations for each visualisation we need to create we would need to create a common locations definition.

Initial requirement description: https://git.unepgrid.ch/grid-p/superset-plugin-chart-mapx/issues/16

#### SDK example usage

Here is a candidate usage of a commons locations definition within the sdk:

```js
const mapFlyToOption = mxManager.ask('get_common_location', {iso3: 'JAM', format: 'zoom_and_center'});
mxManager.ask('map_fly_to', mapFlyToOption);
```

#### References

- https://unstats.un.org/unsd/methodology/m49
- https://docs.mapbox.com/mapbox-gl-js/example/fitbounds/
- https://docs.mapbox.com/mapbox-gl-js/example/flyto/
- https://github.com/unep-grid/map-x-mgl/tree/master/app/src/js/sdk
